blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name="index"),
    path('author/<name>', views.getauthor, name="author"),
    path('article/<int:id>', views.getsingle, name="single_post"),
    path('topic/<name>', views.getTopic, name="topic"),
    path('login', views.getLogin, name="login"),
    path('logout', views.getlogout, name="logout"),
    path('create', views.getcreate, name="create"),
    path('profile', views.getProfile, name="profile"),
    path('update/<int:id>', views.getUpdate, name="update"),
    path('delete/<int:id>', views.getDelete, name="delete"),
    path('register', views.getRegister, name="register"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
]


# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

source code/Advancing blog Part 1-2/Youtube/djangoblog/blogapp/urls.py
from django.urls import path
from . import views
app_name="blogapp"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('author/<name>', views.getauthor.as_view(), name="author"),
    path('article/<int:id>', views.getsingle.as_view(), name="single_post"),
    path('topic/<name>', views.getTopic, name="topic"),
    path('login', views.getLogin.as_view(), name="login"),
    path('logout', views.getlogout, name="logout"),
    path('create', views.getcreate, name="create"),
    path('profile', views.getProfile, name="profile"),
    path('update/<int:pid>', views.getUpdate, name="update"),
    path('delete/<int:pid>', views.getDelete, name="delete"),
    path('register', views.getRegister, name="register"),
    path('topics', views.getCategory, name="category"),
    path('create/topic', views.createTopic, name="createTopic"),



    #account confirmations
    path('activate/<uid>/<token>', views.activate, name="activate")
]

source code/Part 11/djangoblog/blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('author/<name>', views.getauthor, name="author"),
    path('article/<int:id>', views.getsingle, name="single_post"),
    path('topic/<name>', views.getTopic, name="topic"),
    path('login', views.getLogin, name="login"),
    path('logout', views.getlogout, name="logout")
]

source code/part 7/djangoblog/blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('author/<name>', views.getauthor, name="author"),
    path('article/<int:id>', views.getsingle, name="single_post"),
    path('topic/<name>', views.getsingle, name="topic")
]

source code/Advancing blog Part 1-2/Youtube/djangoblog/blogapp/forms.py
from django import forms
from .models import article, author, category, comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class createForm(forms.ModelForm):
    class Meta:
        model = article
        fields = [
            'title',
            'body',
            'image',
            'category'
        ]


class registerUser(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2'
        ]


class createAuthor(forms.ModelForm):
    class Meta:
        model = author
        fields = [
            'profile_picture',
            'details'
        ]


class categoryForm(forms.ModelForm):
    class Meta:
        model = category
        fields = [
            'name'
        ]

class commentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = [
            'name',
            'email',
            'post_comment'
        ]

source code/Advancing blog Part 2-2/Youtube/djangoblog/blogapp/forms.py
from django import forms
from .models import article, author, category, comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class createForm(forms.ModelForm):
    class Meta:
        model = article
        fields = [
            'title',
            'body',
            'image',
            'category'
        ]


class registerUser(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2'
        ]


class createAuthor(forms.ModelForm):
    class Meta:
        model = author
        fields = [
            'profile_picture',
            'details'
        ]


class categoryForm(forms.ModelForm):
    class Meta:
        model = category
        fields = [
            'name'
        ]

class commentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = [
            'name',
            'email',
            'post_comment'
        ]

source code/Youtube/djangoblog/blogapp/forms.py
from django import forms
from .models import article
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class createForm(forms.ModelForm):
    class Meta:
        model = article
        fields = [
            'title',
            'body',
            'image',
            'category'
        ]


class registerUser(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2'
        ]

source code/Advancing blog Part 1-2/Youtube/djangoblog/blogapp/views.py
from django.shortcuts import render,HttpResponse, Http404, get_object_or_404, redirect
from .models import author, category, article, comment
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .forms import createForm, registerUser, createAuthor, categoryForm, commentForm
from django.contrib import messages
from django.views import View
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.conf import settings
from django.core.mail import send_mail
from .token import activation_token


# Create your views here.
class index(View):
    template_name = "index.html"

    def get(self, request):
        post = article.objects.all()
        search = request.GET.get('q')
        if search:
            post = post.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
        paginator = Paginator(post, 8)  # Show 25 contacts per page

        page = request.GET.get('page')
        total_article = paginator.get_page(page)
        context = {
            "post": total_article
        }
        return render(request, self.template_name, context)


class getauthor(View):
    template = "profile.html"

    def get(self, request, name):
        post_author = get_object_or_404(User, username=name)
        auth = get_object_or_404(author, name=post_author.id)
        post = article.objects.filter(article_author=auth.id)
        context = {
            "auth": auth,
            "post": post
        }
        return render(request, self.template, context)


class getsingle(View):
    def get(self, request, id):
        post = get_object_or_404(article, pk=id)
        first = article.objects.first()
        last = article.objects.last()
        getComment = comment.objects.filter(post=id)
        related = article.objects.filter(category=post.category).exclude(id=id)[:4]
        form = commentForm
        context = {
            "post": post,
            "first": first,
            "last": last,
            "related": related,
            "form": form,
            "comment": getComment
        }
        return render(request, "single.html", context)

    def post(self, request, id):
        post = get_object_or_404(article, pk=id)
        form = commentForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.post = post
            instance.save()
            return redirect('blog:single_post', id=id)


def getTopic(request, name):
    cat = get_object_or_404(category, name=name)
    post = article.objects.filter(category=cat.id)
    paginator = Paginator(post, 4)  # Show 25 contacts per page

    page = request.GET.get('page')
    total_article = paginator.get_page(page)
    return render(request, "category.html", {"post": total_article, "cat": cat})


class getLogin(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:index')
        else:
            return render(request, "login.html")

    def post(self, request):
        user = request.POST.get('user')
        password = request.POST.get('pass')
        auth = authenticate(request, username=user, password=password)
        if auth is not None:
            login(request, auth)
            return redirect('blog:index')
        else:
            messages.add_message(request, messages.ERROR, 'Username or password mismatch')
            return redirect('blog:login')


def getlogout(request):
    logout(request)
    return redirect('blog:index')


def getcreate(request):
    if request.user.is_authenticated:
        u = get_object_or_404(author, name=request.user.id)
        form = createForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.article_author = u
            instance.save()
            return redirect('blog:index')
        return render(request, 'create.html', {"form": form})
    else:
        return redirect('blog:login')


def getUpdate(request, pid):
    if request.user.is_authenticated:
        u = get_object_or_404(author, name=request.user.id)
        post = get_object_or_404(article, id=pid)
        form = createForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.article_author = u
            instance.save()
            messages.success(request, 'Article is updated successfully')
            return redirect('blog:profile')
        return render(request, 'create.html', {"form": form})
    else:
        return redirect('blog:login')


def getDelete(request, pid):
    if request.user.is_authenticated:
        post = get_object_or_404(article, id=pid)
        post.delete()
        messages.warning(request, 'Article is deleted successfully')
        return redirect('blog:profile')
    else:
        return redirect('blog:login')


def getProfile(request):
    if request.user.is_authenticated:
        user = get_object_or_404(User, id=request.user.id)
        author_profile = author.objects.filter(name=user.id)
        if author_profile:
            authorUser = get_object_or_404(author, name=request.user.id)
            post = article.objects.filter(article_author=authorUser.id)
            return render(request, 'logged_in_profile.html', {"post": post, "user": authorUser})
        else:
            form = createAuthor(request.POST or None, request.FILES or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.name = user
                instance.save()
                messages.success(request, 'Author profile is created successfully')
                return redirect('blog:profile')
            return render(request, 'createauthor.html', {"form": form})

    else:
        return redirect('blog:login')


def getRegister(request):
    form = registerUser(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.is_active = False
        instance.save()
        site=get_current_site(request)
        mail_subject="Confirmation message for blog"
        message=render_to_string('confirm_email.html',{
            "user":instance,
            'domain':site.domain,
            'uid':instance.id,
            'token':activation_token.make_token(instance)
        })
        to_email=form.cleaned_data.get('email')
        to_list=[to_email]
        from_email=settings.EMAIL_HOST_USER
        send_mail(mail_subject, message, from_email, to_list, fail_silently=True)
        return HttpResponse("<h1>Thanks for your registration. A confirmation link was sent to your email</h1>")
    return render(request, 'register.html', {"form": form})


def getCategory(request):
    query = category.objects.all()
    return render(request, 'topics.html', {"topic": query})


def createTopic(request):
    if request.user.is_authenticated:
        if request.user.is_staff or request.user.is_superuser:
            form = categoryForm(request.POST or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                messages.success(request, 'topic is created!')
                return redirect('blog:category')
            return render(request, 'create_topics.html', {"form": form})
        else:
            raise Http404('You are not authorized to access this page')
    else:
        return redirect('blog:login')


def activate(reuest):
    return render_to_string()

source code/Part 11/djangoblog/blogapp/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import author, category, article
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
# Create your views here.
def index(request):
    post=article.objects.all()
    context={
        "post":post
    }
    return render(request, "index.html", context)

def getauthor(request, name):
    post_author=get_object_or_404(User, username=name)
    auth=get_object_or_404(author, name=post_author.id)
    post=article.objects.filter(article_author=auth.id)
    context={
        "auth":auth,
        "post":post
    }
    return render(request, "profile.html", context)

def getsingle(request, id):
    post=get_object_or_404(article, pk=id)
    first=article.objects.first()
    last=article.objects.last()
    related=article.objects.filter(category=post.category).exclude(id=id)[:4]
    context={
        "post":post,
        "first":first,
        "last":last,
        "related":related
    }
    return render(request, "single.html", context)

def getTopic(request, name):
    cat=get_object_or_404(category, name=name)
    post=article.objects.filter(category=cat.id)
    return render(request, "category.html",{"post":post, "cat":cat})


def getLogin(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == "POST":
            user = request.POST.get('user')
            password = request.POST.get('pass')
            auth = authenticate(request, username=user, password=password)
            if auth is not None:
                login(request, auth)
                return redirect('index')
    return render(request, "login.html")

def getlogout(request):
    logout(request)
    return redirect('index')

source code/djangoblog/djangoblog/blogapp/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import author, category, article
# Create your views here.
def index(request):
    post=article.objects.all()
    context={
        "post":post
    }
    return render(request, "index.html", context)

def getauthor(request, name):
    return render(request, "profile.html")

def getsingle(request, id):
    post=get_object_or_404(article, pk=id)
    first=article.objects.first()
    last=article.objects.last()
    related=article.objects.filter(category=post.category).exclude(id=id)[:4]
    context={
        "post":post,
        "first":first,
        "last":last,
        "related":related
    }
    return render(request, "single.html", context)

def getTopic(request, name):
    cat=get_object_or_404(category, name=name)
    post=article.objects.filter(category=cat.id)
    return render(request, "category.html",{"post":post, "cat":cat})

source code/part 7/djangoblog/blogapp/views.py
from django.shortcuts import render, HttpResponse
from .models import author, category, article
# Create your views here.
def index(request):
    post=article.objects.all()
    context={
        "post":post
    }
    return render(request, "index.html", context)

def getauthor(request, name):
    return render(request, "profile.html")

def getsingle(request, id):
    return render(request, "single.html")

def getTopic(request, name):
    return render(request, "category.html")

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

  <!--
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE
	DESIGNED & DEVELOPED by FREEHTML5.CO

	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<!-- Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,700' rel='stylesheet' type='text/css'>
	<!-- Animate -->
        {% load static %}
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon -->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheet %}

    {% endblock %}


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
	<div id="fh5co-offcanvas">
		<a href="#" class="fh5co-close-offcanvas js-fh5co-close-offcanvas"><span><i class="icon-cross3"></i> <span>Close</span></span></a>
        {% block profile %}

        {% endblock %}
		<div class="fh5co-menu">
			<div class="fh5co-box">
				<h3 class="heading">Menu</h3>
				<ul>
					<li><a href="#">Blog</a></li>
                    <li><a href="{% url 'blog:category' %}">Category</a></li>
					{% if request.user.is_authenticated %}
                        <li><a href="{% url 'blog:profile' %}">Profile</a></li>
                        <li><a href="{% url 'blog:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'blog:login' %}">Login</a></li>
                    {% endif %}
				</ul>
			</div>
			<div class="fh5co-box">
				<h3 class="heading">Search</h3>
				<form action="" method="GET">
					<div class="form-group">
						<input type="text" name="q" class="form-control" placeholder="Type a keyword" value="{{ request.GET.q }}">
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- END #fh5co-offcanvas -->
	<header id="fh5co-header">

		<div class="container-fluid">

			<div class="row">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
				<ul class="fh5co-social">
					<li><a href="#"><i class="icon-twitter"></i></a></li>
					<li><a href="#"><i class="icon-facebook"></i></a></li>
					<li><a href="#"><i class="icon-instagram"></i></a></li>
				</ul>
				<div class="col-lg-12 col-md-12 text-center">
					<h1 id="fh5co-logo"><a href="{% url 'index' %}">Blog</a></h1>
				</div>

			</div>

		</div>

	</header>
    <div class="container-fluid">
		<div class="row fh5co-post-entry">
    {% block content %}

    {% endblock %}
        </div>
    </div>


	<footer id="fh5co-footer">
		<p><small>&copy; 2016. Magazine Free HTML5. All Rights Reserverd. <br> Designed by <a href="http://freehtml5.co" target="_blank">FREEHTML5.co</a>  Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
	</footer>



	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>
    {% block script %}{% endblock %}
	</body>
</html>

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome to our django blog{% endblock %}
{% block stylesheet %}{% endblock %}
{% block content %}
    <h4 class="container">Category: {{ cat.name }}</h4>
    {% for p in post %}
        <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
            <figure>
                <a href="{% url 'blog:single_post' id=p.id %}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
            </figure>
            <span class="fh5co-meta"><a href="{% url 'blog:topic' name=p.category.name %}">{{ p.category.name }}</a></span>
            <h2 class="fh5co-article-title"><a href="{% url 'blog:single_post' id=p.id %}">{{ p.title }}</a></h2>
            <span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
        </article>
    {% endfor %}

<div class="container-fluid">
    <div class="pagination">
    <span class="step-links">
        {% if post.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ post.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post.number }} of {{ post.paginator.num_pages }}.
        </span>

        {% if post.has_next %}
            <a href="?page={{ post.next_page_number }}">next</a>
            <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/confirm_email.html
{% autoescape off %}
Hi {{ user.username }},
Thanks for your registration in blog
Please click on the link below to confirm your registration,
http://{{ domain }}{% url 'blog:activate' uid=uid token=token %}
{% endautoescape %}

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/logged_in_profile.html
{% extends 'base.html' %}
{% block title %}
{{ user.name.get_full_name }}
{% endblock %}
{% block stylesheet %}
    <style>
    .alert {
    height: 50px;
    margin-top: 200px;
}
    </style>
{% endblock %}
{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ user.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ user.name.get_full_name }}</h2>
            <h4>{{ user.name.email }}</h4>
			<p>{{ user.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}
{% block content %}
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container">
        <a href="{% url 'blog:create' %}" class="btn btn-primary pull pull-right">Add new article</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <td>Title</td>
            <td>Posted On</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>
        {% for p in post %}
            <tr>
                <td>{{ p.title }}</td>
                <td>{{ p.posted_on }}</td>
                <td><a href="{% url 'blog:delete' pid=p.id %}">Delete</a>||<a href="{% url 'blog:update' pid=p.id %}">Edit</a></td>
            </tr>
        {% endfor %}

        </tbody>
</table>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/login.html
{% extends 'base.html' %}
{% block title %}Please login{% endblock %}
{% block stylesheet %}
{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please login to your account</h3>
          </div>
          <div class="panel-body">
              {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}
                </div>
                {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" name="user" class="form-control" id="exampleInputEmail1" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="pass" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>

              <button type="submit" class="btn btn-default">Login</button>
              <p>Are you new here? <a href="{% url 'blog:register' %}">Register now</a></p>
            </form>
          </div>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block script %}

{% endblock %}

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Author || {{ auth.name.get_full_name }}
{% endblock %}
{% block stylesheet %}
<style type="text/css">
		#fh5co-offcanvas {
     width: auto;
}
#fh5co-offcanvas .fh5co-menu, #fh5co-offcanvas .fh5co-bio {
    width: auto;
    padding: 50px;
}
    </style>
{% endblock %}
{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ auth.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ auth.name.get_full_name }}</h2>
			<p>{{ auth.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}
{% block content %}
    <h1>Author: {{ auth.name.get_full_name }}</h1>
    {% for p in post %}
        <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
            <figure>
                <a href="{% url 'blog:single_post' id=p.id %}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
            </figure>
            <span class="fh5co-meta"><a href="{% url 'blog:topic' name=p.category.name %}">{{ p.category }}</a></span>
            <h2 class="fh5co-article-title"><a href="{% url 'blog:single_post' id=p.id %}">{{ p.title }}</a></h2>
            <span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
        </article>
    {% endfor %}

{% endblock %}
{% block script %}

{% endblock %}

source code/Advancing blog Part 2-2/Youtube/djangoblog/templates/topics.html
{% extends 'base.html' %}
{% block title %}
All topics
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% if request.user.is_authenticated %}
        {% if request.user.is_staff or request.user.is_superuser %}
            <a href="{% url 'blog:createTopic' %}" class="btn btn-primary pull pull-right">Add new category</a>
        {% endif %}
    {% endif %}

    <table class="table table-striped">
        <thead>
        <tr>
            <td>Topics</td>

            {% if request.user.is_authenticated %}
                {% if request.user.is_staff or request.user.is_superuser %}
                    <td>Action</td>
                {% endif %}
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for t in topic %}
            <tr>
                <td><a href="{% url 'blog:topic' name=t.name %}">{{ t.name }}</a></td>

                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff or request.user.is_superuser %}
                        <td><a href="">Delete</a>||<a href="">Edit</a></td>
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}

        </tbody>
</table>
    </div>
{% endblock %}
{% block script %}

{% endblock %}